name             'webserver'
maintainer       'David Schneider'
maintainer_email 'david.schneider.51063@gmail.com'
license          'All rights reserved'
description      'Installs/Configures a webserver'
long_description 'Installs/Configures a webserver'
version          '0.1.0'
